In [47]:
import numpy as np
import pandas as pd

In [48]:
dataset = pd.read_csv("Fertilizer Prediction.csv")

In [49]:
dataset.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [50]:
dataset['Soil Type'].unique()

array(['Sandy', 'Loamy', 'Black', 'Red', 'Clayey'], dtype=object)

In [51]:
dataset['Crop Type'].unique()

array(['Maize', 'Sugarcane', 'Cotton', 'Tobacco', 'Paddy', 'Barley',
       'Wheat', 'Millets', 'Oil seeds', 'Pulses', 'Ground Nuts'],
      dtype=object)

In [52]:
x= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

In [53]:
x.shape

(99, 8)

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,4])], remainder='passthrough')

In [14]:
from sklearn.naive_bayes import GaussianNB

In [55]:
x= np.array(ct.fit_transform(x))

In [56]:
x.shape

(99, 22)

In [57]:
x[0]

array([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 26, 52, 38, 37, 0, 0], dtype=object)

In [18]:
classifier = GaussianNB()

In [19]:
classifier.fit(x, y)

GaussianNB()

In [22]:
dataset

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
0            26         52        38     Sandy      Maize        37   
1            29         52        45     Loamy  Sugarcane        12   
2            34         65        62     Black     Cotton         7   
3            32         62        34       Red    Tobacco        22   
4            28         54        46    Clayey      Paddy        35   
..          ...        ...       ...       ...        ...       ...   
94           25         50        32    Clayey     Pulses        24   
95           30         60        27       Red    Tobacco         4   
96           38         72        51     Loamy      Wheat        39   
97           36         60        43     Sandy    Millets        15   
98           29         58        57     Black  Sugarcane        12   

    Potassium  Phosphorous Fertilizer Name  
0           0            0            Urea  
1           0           36             DAP  
2           9           30        14-35-14  
3           0           20           28-28  
4           0            0            Urea  
..        ...          ...             ...  
94          0           19           28-28  
95         17           17        10-26-26  
96          0            0            Urea  
97          0           41             DAP  
98          0           10           20-20  

[99 rows x 9 columns]

In [60]:
k = [[26, 52,38, 'Sandy', 'Maize', 37, 0,0]]

In [64]:
k = ct.transform(k)

In [66]:
classifier.predict_proba(k)

array([[0.00000000e+000, 1.38879162e-157, 2.85448720e-070,
        0.00000000e+000, 5.20936069e-046, 0.00000000e+000,
        1.00000000e+000]])

In [40]:
k

array([[1.0, 1.0, 26, 52, 'Sandy', 0, 0]], dtype=object)

In [41]:
ct.get_params

<bound method ColumnTransformer.get_params of ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3, 4])])>

In [67]:
import pickle

In [68]:
pickle.dump(ct, open('fertct.pkl', 'wb'))

In [69]:
pickle.dump(classifier, open('ferpred.pkl', 'wb'))